### ISSUE TITLE
AH incorrect price for some discounted products

### ISSUE THREAD

**Issue by defterade** [m-rtijn/argostime#39] opened 2022-05-15 10:49 UTC
E.g. 

- https://www.ah.nl/producten/product/wi513858/ah-3-laags-toiletpapier
- https://www.ah.nl/producten/product/wi417953/parodontax-original-dagelijkse-tandpasta

Will report a current price of €-1,00 and a lowest price of €9223372036854775808.00.

**Comment by Tweska** [comment] 2022-05-15 12:43
I think this is a duplicate of issue #17.

**Closed** 2022-05-15 14:54 UTC
